export enum EnvironmentVariables {
  ALLOWED_ORIGINS = 'ALLOWED_ORIGINS',
  DATABASE_URL = 'DATABASE_URL',
  REDIS_URL = 'REDIS_URL',
  JWT_PRIVATE = 'JWT_PRIVATE',
  JWT_PUBLIC = 'JWT_PUBLIC',
  FRONTEND_URL = 'FRONTEND_URL',
  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',
  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET',
  GITHUB_CALLBACK_URL = 'GITHUB_CALLBACK_URL',
  TOKEN_TTL = 'TOKEN_TTL',
}

export type PROVIDERS = 'github' | 'google';
export const STRATEGIES: PROVIDERS[] = ['google', 'github'];

export enum AccountProvider {
  CREDENTIALS = 'credentials',
  GOOGLE = 'google',
  GITHUB = 'github',
}
